# Generated by Django 4.2.4 on 2023-11-13 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_baseuser_company_alter_baseuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
