# Generated by Django 4.2.4 on 2023-11-14 08:59

from django.db import migrations, models

def create_chat_options(apps, schema_editor):
    ChatOption = apps.get_model('chathistory', 'ChatOption')
    chat_options = [
    ChatOption(title='Civil Torts in US', prompt='I am here to help you understand civil torts in the US legal system. How can I assist you in exploring the different types of torts and their legal implications?'),
    ChatOption(title='Types of harassment', prompt='I am here to guide you through the various types of harassment, their legal definitions, and your rights under the law. How can I assist you in understanding harassment and possible legal remedies?'),
    ChatOption(title='How does lawsuits work?', prompt='I am here to explain the process of filing and pursuing a lawsuit. How can I assist you in understanding the legal steps involved in starting a lawsuit and what to expect?'),
    ChatOption(title='How do I sue for personal injury?', prompt='I am here to guide you through the process of filing a personal injury lawsuit. How can I assist you in understanding your rights, the evidence you need, and the steps involved in pursuing a personal injury claim?'),
    ChatOption(title='What are the costs of filing a lawsuit?', prompt='I am here to help you understand the costs associated with filing a lawsuit, including legal fees, court costs, and potential expenses. How can I assist you in exploring these financial aspects of litigation?'),
]

    ChatOption.objects.bulk_create(chat_options)

class Migration(migrations.Migration):

    dependencies = [
        ('chathistory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
            ],
        ),
        migrations.RunPython(create_chat_options),
    ]
